### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
We should get a release out that uses more modern dependencies that actually work on jruby 9.2.

This would be needed for https://github.com/jruby/ruby-maven/pull/4.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
I verified that CI is green on my fork: https://github.com/deivid-rodriguez/maven-tools/actions/runs/1413239353.

@mkristian Thoughts on this?

**Review by mkristian — APPROVED** [review]
looks good

**Comment by deivid-rodriguez** [comment]
Great!

Note that I removed `Mavenfile` and `.mvn/extensions.yml` in favor of a plain `pom.xml` file, because I was trying to build my changes, but the problem I'm trying to fix here would prevent me from doing it, because `maven-tools 1.1.6` was being pulled through the `polyglot-ruby` dependency. So to fix it, I opted out of `polyglot-ruby` in this repo.

**Comment by deivid-rodriguez** [comment]
I don't want to abuse your amazing responsiveness, but if we can get this released, I think we will have mostly fixed this change of dependency issues 😃.

**Comment by mkristian** [comment]
@deivid-rodriguez my understanding is that polyglot-ruby is using this gem as well.

**Comment by deivid-rodriguez** [comment]
Yes, exactly, next step would be to bump `polyglot-ruby`'s dependency on this gem after this PR is released. See https://github.com/takari/polyglot-maven/pull/236.

**Comment by mkristian** [comment]
@deivid-rodriguez let me see how to push this rubygems.org - didn't do it for some time.

**Comment by deivid-rodriguez** [comment]
Great, if you need help, let me know!

**Pull request merged**
